// Generated by CoffeeScript 1.10.0
(function() {
  var days_in_month;

  days_in_month = function(year, month) {
    return new Date(year, month, 0).getDate();
  };

  module.exports = function(bytes) {
    var day, month, year;
    if (!bytes) {
      return null;
    }
    if (bytes.length !== 3) {
      return false;
    }
    year = (bytes[0] << 4 | bytes[1] >> 4) - 1024;
    month = (bytes[1] & 0x0F) - 1;
    day = bytes[2] >> 3;
    if (year === -1024) {
      if (month < 1 || month > 12 || day > days_in_month(2000, month)) {
        return false;
      }
    } else {
      switch (month) {
        case 0x00 - 1:
          if ((year > 1 && year % 10 !== 0) || (year < 1 && year % 10 !== -8) || day > 10) {
            return false;
          }
          break;
        case 0x01 - 1:
          if (day !== 0) {
            return false;
          }
          break;
        case 0x0E - 1:
          return false;
        case 0x0F - 1:
          break;
        default:
          if (year > 0 && day > days_in_month(year, month)) {
            return false;
          }
      }
    }
    return true;
  };

}).call(this);
