// Generated by CoffeeScript 1.10.0
(function() {
  var z_pad;

  z_pad = function(number) {
    var str;
    str = '0' + number;
    return str.substr(str.length - 2);
  };

  module.exports = function(bytes) {
    var before_christ, day, month, result, year;
    if (!bytes) {
      return null;
    }
    year = (bytes[0] << 4 | bytes[1] >> 4) - 1024;
    month = (bytes[1] & 0x0F) - 1;
    day = bytes[2] >> 3;
    if (year === -1024) {
      result = "d-" + month;
      if (day > 0) {
        result += "-" + day;
      }
    } else {
      before_christ = year < 1;
      switch (month) {
        case 0x00 - 1:
          if (before_christ) {
            result = -8 - year + "sBC";
          } else {
            result = (year === 1 ? 0 : year) + "s";
          }
          if (day > 0) {
            result += "+" + 10 * day;
          }
          break;
        case 0x01 - 1:
          result = before_christ ? 1 - year + "BC" : "" + year;
          break;
        case 0x0F - 1:
          result = (before_christ ? 1 - year + "BC" : "" + year) + "+" + (day + 1);
          break;
        default:
          result = (before_christ ? 1 - year + "BC" : "" + year) + "-" + z_pad(month);
          if (day > 0) {
            result += "-" + z_pad(day);
          }
      }
    }
    if (!(bytes[2] & 0x02)) {
      result = 'c.' + result;
    }
    if (!(bytes[2] & 0x04)) {
      result = '?' + result;
    }
    if (!(bytes[2] & 0x01)) {
      result = 'fl.' + result;
    }
    return result;
  };

}).call(this);
