// Generated by CoffeeScript 1.10.0
(function() {
  var binary_from_string;

  binary_from_string = require('./binary_from_string');

  module.exports = function(input) {
    var bytes;
    bytes = binary_from_string(input);
    if (!bytes) {
      return null;
    }
    return bytes[0] * 256 * 256 + bytes[1] * 256 + bytes[2];
  };

}).call(this);
