// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(input) {
    if (!input) {
      return null;
    }
    return input[0] * 256 * 256 + input[1] * 256 + input[2];
  };

}).call(this);
