// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(bytes) {
    var before_christ, day, month, result, year;
    if (!bytes) {
      return null;
    }
    if (!bytes.length) {
      bytes = [~~(bytes / 256 / 256), ~~(bytes / 256 % 256), bytes % 256];
    }
    year = (bytes[0] << 4 | bytes[1] >> 4) - 1024;
    month = (bytes[1] & 0x0F) - 1;
    day = bytes[2] >> 3;
    if (year === -1024) {
      return null;
    } else {
      before_christ = year < 1;
      switch (month) {
        case 0x00 - 1:
          if (before_christ) {
            result = -8 - year + "sBC";
          } else {
            return (year === 1 ? 0 : year) + "s";
          }
          break;
        case 0x01 - 1:
          result = before_christ ? 1 - year + "BC" : "" + year;
          break;
        case 0x0F - 1:
          result = (before_christ ? 1 - year + "BC" : "" + year);
          break;
        default:
          result = (before_christ ? 1 - year + "BC" : "" + year);
      }
    }
    return result;
  };

}).call(this);
